//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutupLongLink.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b38880d274a8bd8e710bf1c47369242b")]
        public string UserShortestAPIKey {
            get {
                return ((string)(this["UserShortestAPIKey"]));
            }
            set {
                this["UserShortestAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4035c8e1d3931ac1fec5f8d1cec122c1")]
        public string UserAdflyAPIKey {
            get {
                return ((string)(this["UserAdflyAPIKey"]));
            }
            set {
                this["UserAdflyAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81ec9a87936f0b502f75cb6df8e71512aacddd6e")]
        public string UserR7APIKey {
            get {
                return ((string)(this["UserR7APIKey"]));
            }
            set {
                this["UserR7APIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1503418")]
        public string UserAdflyUID {
            get {
                return ((string)(this["UserAdflyUID"]));
            }
            set {
                this["UserAdflyUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5d4bbf600d064db3a3ccb0e76e9e3180")]
        public string UserRebrandlyAPIKey {
            get {
                return ((string)(this["UserRebrandlyAPIKey"]));
            }
            set {
                this["UserRebrandlyAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("544e7626db6de7861adf6e682e380dbff47890d4")]
        public string UserbitlyAPIKey {
            get {
                return ((string)(this["UserbitlyAPIKey"]));
            }
            set {
                this["UserbitlyAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20f07f91f3303b2f66ab6f61698d977d69b83d64")]
        public string UserPicSeeAPIKey {
            get {
                return ((string)(this["UserPicSeeAPIKey"]));
            }
            set {
                this["UserPicSeeAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserBlinkEmail {
            get {
                return ((string)(this["UserBlinkEmail"]));
            }
            set {
                this["UserBlinkEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserBlinkAPI {
            get {
                return ((string)(this["UserBlinkAPI"]));
            }
            set {
                this["UserBlinkAPI"] = value;
            }
        }
    }
}
