//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShutupLongLink.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b38880d274a8bd8e710bf1c47369242b")]
        public string UserShortestAPIKey {
            get {
                return ((string)(this["UserShortestAPIKey"]));
            }
            set {
                this["UserShortestAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4035c8e1d3931ac1fec5f8d1cec122c1")]
        public string UserAdflyAPIKey {
            get {
                return ((string)(this["UserAdflyAPIKey"]));
            }
            set {
                this["UserAdflyAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("81ec9a87936f0b502f75cb6df8e71512aacddd6e")]
        public string UserR7APIKey {
            get {
                return ((string)(this["UserR7APIKey"]));
            }
            set {
                this["UserR7APIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1503418")]
        public string UserAdflyUID {
            get {
                return ((string)(this["UserAdflyUID"]));
            }
            set {
                this["UserAdflyUID"] = value;
            }
        }
    }
}
